version: 2
jobs:
  build:
    working_directory: ~/django-sagepaypi
    docker:
      - image: themattrix/tox
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
    steps:
      - checkout
      - run: apt update && apt install -y postgresql-client libpq-dev
      - run: pip install --upgrade codecov
      - run: tox -v
      - run: codecov
      - store_test_results:
          path: htmlcov
      - store_artifacts:
          path: htmlcov
          destination: coverage